spring:
  rabbitmq: #mq
    port: 5672
    host: 120.79.38.140
    username: admin
    password: admin
#1.自定义访问规则
zuul:
  routes:
# 1.1详细写法
    myProduct:
      path: /myorders/**
      serviceId: order
      sensitiveHeaders: #不过滤Cookie", "Set-Cookie", "Authorization
#1.2便捷写法
#   order: /myorders/**
  ignored-patterns: #禁止访问,填写的是set值
#     - /myorders/env/print
#     - /**/env/print
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
env: asd
