spring:
  application:
    name: ORDER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8
  rabbitmq:
    port: 5672
    host: 120.79.38.140
    username: admin
    password: admin
  jpa:
    show-sql: true
server:
  port: 8081
env: tesst
#容错配置项，默认配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    Hystrix1: #指定Hystrix1方法容错时间
      execution:
        isolation:
           thread:
              timeoutInMilliseconds: 3000
